version: "3.3"

services: 
  db:
    image: postgres:12
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  
  backend:
    depends_on: 
      - db
    env_file:
      - .env
    build: ./backend
    ports: 
      - 8000:8000

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports: 
      - 0.0.0.0:3000:3000